import { expect, test } from "@playwright/test";
import { defaultContent } from "../../src/data/defaultContent";

test("edit preview copy and photos, save and publish", async ({ page }, testInfo) => {
  await page.goto("/studio");
  await page.getByLabel("Studio passphrase").fill("KV-3D0pKUxlx2yC");
  await page.getByRole("button", { name: "Unlock studio" }).click();
  const preview = page.frameLocator(".admin-preview__frame");
  await page.getByRole("tab", { name: "Our Legacy", exact: true }).click();
  const paragraph = preview.locator('[data-cms-text="about.body"]');
  await paragraph.click();
  await preview.getByRole("textbox", { name: "Edit website text" }).fill("We have over 25 years of experience.");
  await preview.getByRole("textbox", { name: "Edit website text" }).press("Enter");
  await expect(page.getByLabel("Text selected in preview")).toHaveValue("We have over 25 years of experience.");
  await paragraph.click();
  await preview.getByRole("textbox", { name: "Edit website text" }).fill("Cancel this edit");
  await preview.getByRole("textbox", { name: "Edit website text" }).press("Escape");
  await expect(paragraph).toHaveText("We have over 25 years of experience.");
  await preview.locator('[data-cms-image="about.image"]').click();
  await expect(page.getByRole("tab", { name: "Images & galleries" })).toHaveAttribute("aria-selected", "true");
  await page.getByLabel("Preview page").selectOption("/about");
  const staticText = preview.locator('[data-cms-text^="textOverrides."]').filter({ hasText: "How we work" }).first();
  await staticText.click();
  await preview.getByRole("textbox", { name: "Edit website text" }).fill("Homes made with care");
  await preview.getByRole("textbox", { name: "Edit website text" }).press("Enter");
  await expect(page.getByLabel("Text selected in preview")).toHaveValue("Homes made with care");
  await expect(preview.getByText("Homes made with care", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Save draft", exact: true }).click();
  await expect(page.getByText(/Draft saved on this browser/)).toBeVisible();
  await page.reload();
  await page.getByRole("button", { name: "Publish", exact: true }).click();
  await expect(page.getByText(/Published\. The public site/)).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath("studio-inline-editor.png"), fullPage: true });
  await page.goto("/");
  await expect(page.getByText("We have over 25 years of experience.", { exact: true })).toBeVisible();
  await page.goto("/about");
  await expect(page.getByText("Homes made with care", { exact: true })).toBeVisible();
});

test("project cards rotate and link to a scrollable accessible gallery", async ({ page }, testInfo) => {
  const content = structuredClone(defaultContent);
  content.developments[0].gallery = [content.developments[1].image, content.developments[2].image];
  await page.goto("/");
  await page.evaluate((data) => localStorage.setItem("kingsvale-site-content-v1", JSON.stringify(data)), content);
  await page.reload();
  const card = page.locator('.project-carousel').first();
  await card.scrollIntoViewIfNeeded();
  await page.mouse.move(0, 0);
  await expect(card.locator('.project-carousel__controls > span')).toHaveText("2 / 3", { timeout: 12000 });
  await card.getByRole("button", { name: "Next The Ridings photograph" }).click();
  await expect(card.locator('.project-carousel__controls > span')).toHaveText("3 / 3");
  await card.getByRole("link", { name: "View The Ridings gallery" }).click();
  await expect(page).toHaveURL(/ridings#gallery$/);
  const gallery = page.getByRole("region", { name: "The Ridings image gallery", exact: true });
  await gallery.getByRole("button", { name: /Show photograph 2:/ }).click();
  await expect(gallery.getByRole("button", { name: /Show photograph 2:/ })).toHaveAttribute("aria-pressed", "true");
  await page.getByRole("region", { name: "Scrollable project photographs" }).focus();
  await page.keyboard.press("ArrowRight");
  await expect(gallery.getByRole("button", { name: /Show photograph 3:/ })).toHaveAttribute("aria-pressed", "true");
  await gallery.getByRole("button", { name: "Enlarge photograph 3" }).click();
  await expect(page.getByRole("dialog")).toBeVisible();
  await page.keyboard.press("Escape");
  await expect(page.getByRole("dialog")).not.toBeVisible();
  await expect(gallery.getByRole("button", { name: "Enlarge photograph 3" })).toBeFocused();
  await page.screenshot({ path: testInfo.outputPath("project-gallery.png"), fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false);
});
import sharp from "sharp";

test("browse mode stays in the draft preview and reduced motion stops autoplay", async ({ page }) => {
  await page.goto("/studio");
  await page.getByLabel("Studio passphrase").fill("KV-3D0pKUxlx2yC");
  await page.getByRole("button", { name: "Unlock studio" }).click();
  await page.getByRole("button", { name: "Browse website", exact: true }).click();
  const preview = page.frameLocator(".admin-preview__frame");
  await preview.getByRole("link", { name: "Discover our developments" }).click();
  await expect(preview.locator("html")).toHaveAttribute("data-studio-inline", "false");
  await expect(preview.getByRole("heading", { name: "Distinctive homes in carefully chosen locations." })).toBeVisible();
  await page.getByRole("button", { name: "Click to edit", exact: true }).click();
  await preview.getByRole("heading", { name: "Distinctive homes in carefully chosen locations." }).click();
  await expect(preview.getByRole("textbox", { name: "Edit website text" })).toBeVisible();
  await page.emulateMedia({ reducedMotion: "reduce" });
  await page.goto("/");
  const content = structuredClone(defaultContent);
  content.developments[0].gallery = [content.developments[1].image];
  await page.evaluate((data) => localStorage.setItem("kingsvale-site-content-v1", JSON.stringify(data)), content);
  const png = await sharp({ create: { width: 100, height: 60, channels: 3, background: "#789175" } }).png().toBuffer();
  await page.route("**/images.unsplash.com/**", (route) => route.fulfill({ contentType: "image/png", body: png }));
  await page.reload();
  const card = page.locator(".project-carousel").first();
  await card.scrollIntoViewIfNeeded();
  await expect(card.getByRole("button", { name: /slideshow/ })).toHaveCount(0);
  await page.clock.install();
  await page.clock.fastForward(15000);
  await expect(card.locator(".project-carousel__controls > span")).toHaveText("1 / 2");
});
